### ISSUE TITLE
Getting Notice on Settings Page

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#12]
Notice: Undefined index: adminer in /Applications/XAMPP/ds-plugins/clean-import/page.php on line 65

![screen shot 2017-06-16 at 12 56 25 pm](https://user-images.githubusercontent.com/1041421/27242742-665b98ea-5293-11e7-9f34-14ef91cba473.jpg)

**Comment by davejesch** [comment]
Is there a clean-import-settings.json file in the ds-plugins/clean-import/ directory? If not, can you copy this in from the previous version? And does that make any difference? I think this is caused when the .json file doesn't exist but want to make sure. If so, it's easily fixed.

**Comment by GreggFranklin** [comment]
There is not a clean-import-settings.json file. I could not find one in the previous version either.

**Comment by davejesch** [comment]
Use the WP dashboard and save the settings- that will create the file. Then, go to the DS Tools page and see if the error persists.

**Comment by GreggFranklin** [comment]
That resolved it.

**Comment by davejesch** [comment]
kk. I'll have a fix in a bit. The you can verify by deleting the .json file and recreating original issue.

**Comment by GreggFranklin** [comment]
Issue resolved.
