### ISSUE TITLE
Clean Imports setting page does not produce an admin notice that the settings have been saved.

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#13]
#### STEPS TO REPRODUCE: 
Go to Tools in the Dashboard or Tools in the Localhost page and Click on DS Clean Import
Change some settings
Click the [ Save Changes ] button

#### RESULTS: 
There is no indication that the settings ere saved.

#### EXPECTED RESULT:
Most plugins including our own Admin color bar will produce the "Settings saved." banner

![screen shot 2017-07-12 at 6 28 05 am](https://user-images.githubusercontent.com/1041421/28120056-cc52a214-66cb-11e7-8bcf-b76e44d942cb.jpg)

**Comment by davejesch** [comment]
added message

**Comment by GreggFranklin** [comment]
Test and successful.
