### ISSUE TITLE
Options to clear logs from popular plugins on import

### ISSUE THREAD

**Issue by davejesch** [ServerPress/clean-import#18]
#### STEPS TO REPRODUCE: 
1. Import archive containing large log files, from iThemes Security, WordFence, etc.

#### RESULTS: 
Can cause imports to crash due to large database size.

#### EXPECTED RESULT:
Need option to disable the import of logging from some of the popular plugins. We need more research to determine exactly which ones we can ignore (not just security logs, but transaction logs from eCommerce platforms, view logs from forms plugins, etc.) and how we want to ignore them. i.e. do we: Edit the .sql files and remove them? Truncate the table after the import?

**Comment by GreggFranklin** [comment]
Implemented in v1.1.5
