### ISSUE TITLE
Issuing a WP-CLI command when Clean-import and DS-CLI are active produce the wp-config.php file output

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#19]
#### STEPS TO REPRODUCE: 
1. Activate Clean Import and DS-CLI
2. Visit any sites DS-CLI > Terminal
3. At the Prompt type: WP

#### RESULTS: 
Outputs the wp-config.php file

#### EXPECTED RESULT:
Should output WP-CLI's WP Description, Synopsis and Subcommands

**Comment by davejesch** [comment]
Issue moved to [ServerPress/databasecollationfix #6](https://github.com/ServerPress/databasecollationfix/issues/6) via [**ZenHub**](https://www.zenhub.com/)
