### ISSUE TITLE
Duplicator now renames the wp-config.php file to wp-config-arc.txt

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#22]
This creates an error because DesktopServer cannot find the wp-config.php file.

If we could rename this before importing would resolve this issue.

**Comment by davejesch** [comment]
Side question: after you run the Duplicator import on the Target domain, is it renaming wp-config-arc.txt to wp-config.php? Or is there a wp-config-arc.txt file left after the import? What if there's an error during the import process?

I ask, because this could be a security issue with Duplicator. If it ever leaves a .txt file around it could expose database passwords.

**Comment by GreggFranklin** [comment]
Not sure have never used the Duplicator import.

**Comment by GreggFranklin** [comment]
Related to: https://github.com/ServerPress/ds/issues/159

**Comment by GreggFranklin** [comment]
Duplicator light does not appear to change the wp-config.php files name. ( https://wordpress.org/plugins/duplicator/ ) The pro version changes the name to  dup-wp-config-arc__8bde909-07151227.txt. I thought I had originally seen it as wp-config-arc-txt. But the provided link below with an archive has the first one. 

https://www.dropbox.com/s/g7hno6g6nhc7l0b/20180807_ivac_8bde9098ed0cd5fe4800_20180807151227_archive.zip?dl=0

We may want to check for both dup-wp-config-arc__8bde909-07151227.txt and wp-config-arc.txt

**Comment by davejesch** [comment]
Also renamed the .sql file found in the dup-installer/ directory. It had the same "guid" built into the file name.

I do not have an example of the wp-config-arc.txt file and the name of the .sql file for that scenario. I did add code to rename wp-config-arc.txt and that works but I'm not sure of the .sql file name so I'll need an example of that.

**Comment by GreggFranklin** [comment]
In the archive provided above contains the modified wp-config.php file. It is named: **dup-wp-config-arc__8bde909-07151227.txt**

**Comment by GreggFranklin** [comment]
The database is located in /dup-installer and named dup-database__8bde909-07151227.sql also can be found in archive provided.

**Comment by GreggFranklin** [comment]
When using the archive provide in this thread I received the following error after installing the latest master. *The database.sql may have to be put in the root of the folder.

![image 12](https://user-images.githubusercontent.com/1041421/44542516-dfe49a80-a6c1-11e8-93ec-249e93362e68.jpg)

**Comment by davejesch** [comment]
@GreggFranklin I am moving the .sql file to the main folder and renaming it to database.sql. The behavior you're describing is what I saw before I added the code to renamed/moved the files. So you might not have installed the current code correctly. Check that first.

If that doesn't do it then try this: in prepend.php there's a debug() method. Comment out the return on line 351. Also comment out the if() test on 352 and the close brace on 365. This will create a log file named ds-plugins/~clean-import-log.txt. Run the import again and attach the log file here.

**Comment by GreggFranklin** [comment]
OS: Mac

I did as instructed:
![screen shot 2018-08-23 at 7 20 12 pm](https://user-images.githubusercontent.com/1041421/44561480-e1d24c00-a709-11e8-90fc-e2a63ebc9d48.jpg)

No log fine is created:
![screen shot 2018-08-23 at 7 22 04 pm](https://user-images.githubusercontent.com/1041421/44561483-ebf44a80-a709-11e8-9ba2-fcf70902810a.jpg)

**Comment by davejesch** [comment]
@GreggFranklin As stated above, the log file is created in ds-plugins/~clean-import-log.php -- not ds-plugins/clean-import/~clean-import-log.txt

**Comment by GreggFranklin** [comment]
Issue resolved
