### ISSUE TITLE
Present an alert if the client has installed the Clean Import in WordPress instead of in the ds-plugins folder

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#24]
STEPS TO REPRODUCE:

    Download plugin and install via WordPress.

RESULT:

An error is produced
EXPECTED RESULT:

An alert instructing them to install it in OS path \ ds-plugins

![screen shot 2018-06-12 at 7 55 40 am](https://user-images.githubusercontent.com/1041421/41298347-07cec7bc-6e16-11e8-95bd-eb1567332352.jpg)

**Comment by davejesch** [comment]
added message

**Comment by GreggFranklin** [comment]
Plugin could not be activated because it triggered a fatal error.

( ! ) Fatal error: Uncaught Error: Using $this when not in object context in /Users/GreggFranklin/Documents/Websites/test99.dev.cc/wp-content/plugins/clean-import-master/clean-import.php on line 16
( ! ) Error: Using $this when not in object context in /Users/GreggFranklin/Documents/Websites/test99.dev.cc/wp-content/plugins/clean-import-master/clean-import.php on line 16
Call Stack
#	Time	Memory	Function	Location
1	0.0388	648576	{main}( )	.../plugins.php:0
2	0.5825	24550568	plugin_sandbox_scrape( )	.../plugins.php:172
3	0.5827	24554680	include( '/Users/GreggFranklin/Documents/Websites/test99.dev.cc/wp-content/plugins/clean-import-master/clean-import.php' )	.../plugin.php:1897

**Comment by davejesch** [comment]
fixed callback reference

**Comment by GreggFranklin** [comment]
Issue resolved
