### ISSUE TITLE
Add pre-processing of database.sql to remove unnecessary data

### ISSUE THREAD

**Issue by davejesch** [ServerPress/clean-import#25]
#### STEPS TO REPRODUCE: 
1. Import database from HelpScout issue 201379

#### RESULTS: 
Many large tables are declared for this database. We can remove a lot of this data such as:
- prli_clicks
- itsec_distributed_storage
- itsec_lockouts
- itsec_log
- itsec_logs
- itsec_temp
- tve_leads_event_log
- wfFileMods
- wfHoover
- rg_form_view

#### EXPECTED RESULT:
Tables with large amounts of log information do not need to be imported. Once we have some pre-import hooks these could be removed.

HelpScout issue: 201379
https://www.dropbox.com/s/a00a876n287cwmv/thewaystowealth.com.zip?dl=0
(note: link no longer works)

**Comment by davejesch** [comment]
implemented

**Comment by GreggFranklin** [comment]
Testing and functions.
