### ISSUE TITLE
Importing sites with ENGINE=Aria fails

### ISSUE THREAD

**Issue by davejesch** [ServerPress/clean-import#26]
#### STEPS TO REPRODUCE: 
1. import site with ENGINE=Aria

#### RESULTS: 
Produces errors

#### EXPECTED RESULT:
Change ENGINE= to InnoDB before import is performed

Reported: https://github.com/ServerPress/ds/issues/89

**Comment by davejesch** [comment]
fixed

**Comment by davejesch** [comment]
fixed

**Comment by erinmarinas** [comment]
Tested. Issue resolved.
