### ISSUE TITLE
".htacces" typo on Clean Import plugin description

### ISSUE THREAD

**Issue by davejesch** [ServerPress/clean-import#29]
@erinmarinas commented on [Fri Aug 24 2018](https://github.com/ServerPress/ds/issues/183)

#### STEPS TO REPRODUCE: 
1. Start DesktopServer
2.  Click on the Clean Import plugin to bring up the plugin description

#### RESULT: 
![ds1](https://user-images.githubusercontent.com/10032031/44614650-3cc78880-a85b-11e8-93f1-fce402b32f25.png)

**Comment by davejesch** [comment]
Fixed.

This won't be in the build until a couple of the other active issues are verified. You can download the code from the repo and copy it in place to your ds-plugins/ directory to verify though.

**Comment by erinmarinas** [comment]
Fix verified. Closing.
