### ISSUE TITLE
general htaccess file not being created.

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#3]
If a .htaccess file exists it will rename it with the .htaccess-sav-{date/time} but the general .htaccess file is not created. If there is no .htaccess file a general one is not created.

**Comment by GreggFranklin** [comment]
This is an archive that was created by DesktopServer and then reimported back in with the Clean Import.

https://www.dropbox.com/s/oo69y6c6qy5cgmk/www.laurelredevelopment.com-deploy.zip?dl=0

![screen shot 2017-06-08 at 10 12 35 am](https://user-images.githubusercontent.com/1041421/26941351-09aeefd6-4c33-11e7-89ec-8eccb44d4da0.jpg)

**Comment by davejesch** [comment]
Cannot reproduce with provided archive on Windows. Can you try again on Mac and see if it's still happening? I'll try it on Mac tomorrow as well.

**Comment by GreggFranklin** [comment]
Here is a quick video of the Site Root as the archive is being imported.
https://screencast.com/t/FZMP2tGW57n

**Comment by GreggFranklin** [comment]
This issue is now resolved.
