### ISSUE TITLE
Clean Import settings for "Do not import log records:" does not stay set after [ Save Changes ]

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#30]
#### STEPS TO REPRODUCE: 
1. Install/Activate Clean Import
2. Visit settings page on http://localhost under Tools
3. Click the "Yes" radio button
4. Click [ Save Changes ]

![image 23](https://user-images.githubusercontent.com/1041421/44620330-2fa09e80-a847-11e8-994f-d47a0718dad1.jpg)

#### RESULTS: 
Does not save the change.(Yes)
![image 24](https://user-images.githubusercontent.com/1041421/44620335-4810b900-a847-11e8-983f-c36ce629be48.jpg)

#### EXPECTED RESULT:
Save the setting.(Yes)

Operating System:  Windows 10

**Comment by davejesch** [comment]
fixed

**Comment by GreggFranklin** [comment]
This issue has been resolved.
