### ISSUE TITLE
Add the Affiliate WP plugin to the list of plugins to automatically deactivate

### ISSUE THREAD

**Issue by davejesch** [ServerPress/clean-import#32]
#### STEPS TO REPRODUCE: 
1. Import a site with Affiliate WP installed and activated

#### RESULTS: 
Note that the plugin is active.

#### EXPECTED RESULT:
The Affiliate WP plugin needs to be deactivated after Clean Import does it's work.

**Comment by GreggFranklin** [comment]
I created a site 
installed and activated AffiliateWP
added user as affiliate
exported site as archive
reimported site with all plugins on 
Successful import no errors. 
reviewed site and all was well.

**Comment by davejesch** [comment]
@GreggFranklin This may be working since we're using mysqldump to export the tables, as well as views, stored procedures and triggers, etc. now.

Following the above steps with an older version like 3.9.1- does this present a problem? I think it might.

It would also likely create a problem if the site was exported from a live domain using one of several backup tools that do not properly export views. Importing that (technically) mal-formed .sql file will still cause an issue. In this case it's probably best to disable the plugin since the state of the database would not likely result in a properly functioning plugin.

Your thoughts?

By the way, I'm okay not implementing this if it's not needed. But I do recall certain scenarios (as above) where it might still be needed.

**Comment by davejesch** [comment]
Related to https://github.com/ServerPress/ds/issues/108

**Comment by GreggFranklin** [comment]
Affiliate WP no longer creates this issue.
