### ISSUE TITLE
Can't find database from a Duplicator package when custom scrubbing options are turned on. 

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#37]
#### STEPS TO REPRODUCE: 
1. Import a Duplicator package with the Clean Import plugin activated
2. Check the box for Customize scrubbing options

#### RESULTS: 
![image 3](https://user-images.githubusercontent.com/1041421/51287258-771cf800-19ab-11e9-9d60-709717b84ff9.jpg)

#### EXPECTED RESULT:
To import correctly. 

Plugin version: 1.1.6
Operating System: Mac Mojave,

**Comment by Steveorevo** [comment]
Thats not a Mojave screenshot. Are we sure this is on Mojave or is it Windows too? Archive specific or any duplicator archive?

**Comment by GreggFranklin** [comment]
Yes, this happens on both platforms. This was a screen shot from my Windows machine.

**Comment by GreggFranklin** [comment]
Archive: https://www.dropbox.com/s/xff1w53nir9144f/ibs-site.zip?dl=0

**Comment by davejesch** [comment]
@GreggFranklin Is this fixed with the recent changes to #41?

**Comment by GreggFranklin** [comment]
Issue resolved.
