### ISSUE TITLE
Some debugging was discovered when firing up Trace

### ISSUE THREAD

**Issue by davejesch** [ServerPress/clean-import#39]
@GreggFranklin commented on [Tue May 28 2019](https://github.com/ServerPress/ds/issues/255)

#### STEPS TO REPRODUCE: 
1. Start up DesktopServer
2. Turn on the Debug and Trace Plugin
3. Start up Trace

#### RESULT: 
![Image 1](https://user-images.githubusercontent.com/1041421/58528144-44b9ad80-818a-11e9-9dae-831b3d7ce241.jpg)

#### EXPECTED RESULT: 
No output

**Comment by davejesch** [comment]
Messages have been removed.

**Comment by GreggFranklin** [comment]
@davejesch There are lines that say "DS_Clean_Import::debug('***starting');" -- Would these lines to be changed to "self::debug('***starting');" ?

**Comment by davejesch** [comment]
No. Those are outside of the class.

ALL of the messages have been effectively removed by adding a return statement at the top of the DS_Clean_Import::debug() method.

**Comment by GreggFranklin** [comment]
Tested - Issue resolved
