### ISSUE TITLE
Add the option of deactivating LiteSpeed Cache 

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#43]
class DS_Clean_Import_Plugins extends DS_Clean_Import_Base
{
	// non-optional: these plugins will always be disabled due to issues caused by them
	private $_non_optional = array(
'litespeed-cache',	 // LiteSpeed Cache

Also the advance-cache.php file that LiteSpeed Cache adds

	// the following are files that are dependent upon or related to items in the above lists
	private $_dependents = array(
		'litespeed-cache' => 'wp-content/advanced-cache.php',

**Comment by GreggFranklin** [comment]
I pushed this change and wanted you to review.

**Comment by davejesch** [comment]
"Also the advance-cache.php file that LiteSpeed Cache adds"
What about the "advance-cache.php" file? And where is this located?

"I pushed this change and wanted you to review."
What change? Can you add a link to the check-in?

**Comment by GreggFranklin** [comment]
This is working as expected. Including the "advance-cache.php" file which is located in the s /wp-content folder.
