### ISSUE TITLE
Move the JetPack Define to just above the /* That's all, stop editing...

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#5]
I was wondering if it would be possible to move the define down a bit just above the /* That's all, stop editing! Happy blogging. */

![wp-config_php](https://user-images.githubusercontent.com/1041421/26912502-b92cab70-4bc9-11e7-9aab-1a1b3c8a1e5a.png)

**Comment by davejesch** [comment]
Moved the define. But noticed that the the value is being defined as 'TRUE' -- a string, rather than a boolean TRUE. Tried using set_key( 'JETPACK_DEV_DEBUG', TRUE ) and it sets it to a value of '1'. @Steveorevo any thoughts? Is there a way to specify the type for the value sent to set_key()?

**Comment by GreggFranklin** [comment]
Perfect!

![screen shot 2017-06-13 at 12 52 24 pm](https://user-images.githubusercontent.com/1041421/27101574-2d9686fe-5037-11e7-8c30-34b6d579078d.jpg)
