### ISSUE TITLE
There is mention of a help screen above that does nto exist. 

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#9]
Located on the Clean Import Settings page.

![screen shot 2017-06-15 at 10 37 12 pm](https://user-images.githubusercontent.com/1041421/27213387-56bc74c2-521b-11e7-8546-40648f8aafc2.jpg)

**Comment by davejesch** [comment]
added help screens to WP dashboard and DS Tools page

**Comment by GreggFranklin** [comment]
Looks and works great!
